
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox8;

	private global::Gtk.HBox hbox7;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Label label2;

	private global::Gtk.Label label5;

	private global::Gtk.Label label3;

	private global::Gtk.Label label4;

	private global::Gtk.VBox vbox9;

	private global::Gtk.Entry entryNumero1;

	private global::Gtk.Entry entryNumero2;

	private global::Gtk.Label labelResultado;

	private global::Gtk.Table table5;

	private global::Gtk.Button buttonDividir;

	private global::Gtk.Button buttonMultiplica;

	private global::Gtk.Button buttonResta;

	private global::Gtk.Button buttonSuma;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label2 = new global::Gtk.Label();
		this.label2.Name = "label2";
		this.vbox2.Add(this.label2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label5 = new global::Gtk.Label();
		this.label5.Name = "label5";
		this.vbox2.Add(this.label5);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label5]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.vbox2.Add(this.label3);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label3]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Resultado:");
		this.vbox2.Add(this.label4);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label4]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.hbox7.Add(this.vbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.vbox9 = new global::Gtk.VBox();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.entryNumero1 = new global::Gtk.Entry();
		this.entryNumero1.CanFocus = true;
		this.entryNumero1.Name = "entryNumero1";
		this.entryNumero1.IsEditable = true;
		this.entryNumero1.InvisibleChar = '•';
		this.vbox9.Add(this.entryNumero1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.entryNumero1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.entryNumero2 = new global::Gtk.Entry();
		this.entryNumero2.CanFocus = true;
		this.entryNumero2.Name = "entryNumero2";
		this.entryNumero2.IsEditable = true;
		this.entryNumero2.InvisibleChar = '•';
		this.vbox9.Add(this.entryNumero2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.entryNumero2]));
		w7.Position = 1;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.labelResultado = new global::Gtk.Label();
		this.labelResultado.Name = "labelResultado";
		this.vbox9.Add(this.labelResultado);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.labelResultado]));
		w8.Position = 2;
		w8.Expand = false;
		w8.Fill = false;
		this.hbox7.Add(this.vbox9);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.vbox9]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child hbox7.Gtk.Box+BoxChild
		this.table5 = new global::Gtk.Table(((uint)(3)), ((uint)(3)), false);
		this.table5.Name = "table5";
		this.table5.RowSpacing = ((uint)(6));
		this.table5.ColumnSpacing = ((uint)(6));
		// Container child table5.Gtk.Table+TableChild
		this.buttonDividir = new global::Gtk.Button();
		this.buttonDividir.CanFocus = true;
		this.buttonDividir.Name = "buttonDividir";
		this.buttonDividir.UseUnderline = true;
		this.buttonDividir.Label = global::Mono.Unix.Catalog.GetString(" / ");
		this.table5.Add(this.buttonDividir);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table5[this.buttonDividir]));
		w10.TopAttach = ((uint)(1));
		w10.BottomAttach = ((uint)(2));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.buttonMultiplica = new global::Gtk.Button();
		this.buttonMultiplica.CanFocus = true;
		this.buttonMultiplica.Name = "buttonMultiplica";
		this.buttonMultiplica.UseUnderline = true;
		this.buttonMultiplica.Label = global::Mono.Unix.Catalog.GetString(" * ");
		this.table5.Add(this.buttonMultiplica);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table5[this.buttonMultiplica]));
		w11.LeftAttach = ((uint)(1));
		w11.RightAttach = ((uint)(2));
		w11.XOptions = ((global::Gtk.AttachOptions)(4));
		w11.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.buttonResta = new global::Gtk.Button();
		this.buttonResta.CanFocus = true;
		this.buttonResta.Name = "buttonResta";
		this.buttonResta.UseUnderline = true;
		this.buttonResta.Label = global::Mono.Unix.Catalog.GetString(" - ");
		this.table5.Add(this.buttonResta);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table5[this.buttonResta]));
		w12.TopAttach = ((uint)(1));
		w12.BottomAttach = ((uint)(2));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.buttonSuma = new global::Gtk.Button();
		this.buttonSuma.CanFocus = true;
		this.buttonSuma.Name = "buttonSuma";
		this.buttonSuma.UseUnderline = true;
		this.buttonSuma.Label = global::Mono.Unix.Catalog.GetString(" + ");
		this.table5.Add(this.buttonSuma);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table5[this.buttonSuma]));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		this.hbox7.Add(this.table5);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.table5]));
		w14.Position = 2;
		this.vbox8.Add(this.hbox7);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox7]));
		w15.Position = 0;
		w15.Expand = false;
		w15.Fill = false;
		this.Add(this.vbox8);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 298;
		this.DefaultHeight = 86;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.buttonSuma.Clicked += new global::System.EventHandler(this.OnButtonSumaClicked);
		this.buttonResta.Clicked += new global::System.EventHandler(this.OnButtonRestaClicked);
		this.buttonMultiplica.Clicked += new global::System.EventHandler(this.OnButtonMultiplicaClicked);
		this.buttonDividir.Clicked += new global::System.EventHandler(this.OnButtonDividirClicked);
	}
}
