
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.Label labelNumero;

	private global::Gtk.Button buttonAdelante;

	private global::Gtk.Table table;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button buttonReiniciar;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.labelNumero = new global::Gtk.Label();
		this.labelNumero.Name = "labelNumero";
		this.labelNumero.LabelProp = global::Mono.Unix.Catalog.GetString("Pulsa Adelante para comenzar");
		this.hbox1.Add(this.labelNumero);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.labelNumero]));
		w1.Position = 1;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.buttonAdelante = new global::Gtk.Button();
		this.buttonAdelante.CanFocus = true;
		this.buttonAdelante.Name = "buttonAdelante";
		this.buttonAdelante.UseStock = true;
		this.buttonAdelante.UseUnderline = true;
		this.buttonAdelante.Label = "gtk-go-forward";
		this.hbox1.Add(this.buttonAdelante);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.buttonAdelante]));
		w2.Position = 2;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox1.Add(this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.table = new global::Gtk.Table(((uint)(9)), ((uint)(10)), true);
		this.table.Name = "table";
		this.table.RowSpacing = ((uint)(6));
		this.table.ColumnSpacing = ((uint)(6));
		this.table.BorderWidth = ((uint)(6));
		this.vbox1.Add(this.table);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.table]));
		w4.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.buttonReiniciar = new global::Gtk.Button();
		this.buttonReiniciar.CanFocus = true;
		this.buttonReiniciar.Name = "buttonReiniciar";
		this.buttonReiniciar.UseUnderline = true;
		this.buttonReiniciar.Label = global::Mono.Unix.Catalog.GetString("Reiniciar");
		this.hbox2.Add(this.buttonReiniciar);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonReiniciar]));
		w5.PackType = ((global::Gtk.PackType)(1));
		w5.Position = 2;
		w5.Expand = false;
		this.vbox1.Add(this.hbox2);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w6.Position = 2;
		w6.Expand = false;
		w6.Fill = false;
		this.Add(this.vbox1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
	}
}
